name: Health check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2.2
        with:
          url: https://boiling-springs-43350.herokuapp.com/health

